#!/usr/bin/env bash
# Interactive setup wizard — prompts for everything provision-mudi.sh needs
# and writes mudi.env (mode 600). Run again later to edit; existing values
# are shown as defaults so you can hit Enter to keep them.

set -u

ENV_FILE="${MUDI_ENV:-mudi.env}"

declare -A EXISTING
if [ -f "$ENV_FILE" ]; then
    while IFS='=' read -r k v; do
        case "$k" in ''|'#'*) continue ;; esac
        v="${v%\"}"; v="${v#\"}"
        EXISTING[$k]="$v"
    done < "$ENV_FILE"
    echo "Loaded existing $ENV_FILE — current values will be shown as defaults."
    echo
fi

ask() {
    local var="$1" hint="$2" fallback="${3:-}" mode="${4:-show}"
    local def="${EXISTING[$var]:-$fallback}" val prompt

    prompt="  $var"
    [ -n "$hint" ] && prompt+=" — $hint"
    if [ "$mode" = "secret" ] && [ -n "$def" ]; then
        prompt+=" [press Enter to keep existing]"
    elif [ -n "$def" ]; then
        prompt+=" [$def]"
    fi
    prompt+=": "

    # NOTE: read -p writes the prompt to stderr (preserved); the trailing
    # newline echo MUST go to stderr too, otherwise command-substitution
    # ($(ask ...)) captures it into the returned value.
    if [ "$mode" = "secret" ]; then
        read -r -s -p "$prompt" val
        printf '\n' >&2
    else
        read -r -p "$prompt" val
    fi
    [ -z "$val" ] && val="$def"
    printf '%s' "$val"
}

valid_ipv4() {
    [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
    local IFS=. ; for o in $1; do (( o <= 255 )) || return 1; done
}

valid_uuid() {
    [[ "$1" =~ ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ ]]
}

gen_random_token() {
    head -c 16 /dev/urandom 2>/dev/null | base64 | tr -d '/+=' | head -c 22
}

cat <<'BANNER'
═══════════════════════════════════════════════════════════════
 mudi7-smart-gateway setup wizard
═══════════════════════════════════════════════════════════════
Press Enter to keep the bracketed default. Ctrl-C to abort.

BANNER

echo "── VPS ──"
while :; do
    VPS_HOST=$(ask VPS_HOST "your VPS hostname (e.g. proxy.example.com)")
    [ -n "$VPS_HOST" ] && break
    echo "  VPS_HOST is required."
done
while :; do
    VPS_IP=$(ask VPS_IP "VPS public IPv4")
    if valid_ipv4 "$VPS_IP"; then break
    else echo "  '$VPS_IP' is not a valid IPv4 address."
    fi
done

echo
echo "── VLESS + REALITY (primary proxy) ──"
VLESS_PORT=$(ask VLESS_PORT "TCP port sing-box listens on" 8443)
while :; do
    VLESS_UUID=$(ask VLESS_UUID "sing-box generate uuid")
    if valid_uuid "$VLESS_UUID"; then break
    else echo "  Not a UUID. Format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    fi
done
VLESS_PUBKEY=$(ask VLESS_PUBKEY "REALITY public key from VPS")
VLESS_SHORTID=$(ask VLESS_SHORTID "REALITY short-id (hex)")
VLESS_SNI=$(ask VLESS_SNI "spoofed SNI (any REALITY-compatible host)" "www.microsoft.com")

echo
echo "── Hysteria-2 (fallback proxy) ──"
HY2_PORT=$(ask HY2_PORT "UDP port for Hy2" 443)
HY2_PASSWORD=$(ask HY2_PASSWORD "Hy2 password" "" secret)

echo
echo "── mihomo external-controller API ──"
API_SECRET_DEFAULT="${EXISTING[API_SECRET]:-$(gen_random_token)}"
API_SECRET=$(ask API_SECRET "LAN-only API bearer (random suggested)" "$API_SECRET_DEFAULT")

echo
echo "── Tailscale (optional, leave blank to skip Phase 9) ──"
echo "  Get an official auth key at https://login.tailscale.com/admin/settings/keys"
echo "  (or set TS_LOGIN_SERVER below to use self-hosted Headscale)"
TS_AUTHKEY=$(ask TS_AUTHKEY "tskey-auth-... from Tailscale or Headscale" "" secret)
TS_LOGIN_SERVER=$(ask TS_LOGIN_SERVER "control plane URL" "${EXISTING[TS_LOGIN_SERVER]:-https://login.tailscale.com}")

# Write the file atomically.
TMP_FILE=$(mktemp "${ENV_FILE}.XXXXXX")
trap 'rm -f "$TMP_FILE"' EXIT
{
    echo "# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# DO NOT COMMIT — this file is gitignored by default."
    echo
    echo "VPS_HOST=$VPS_HOST"
    echo "VPS_IP=$VPS_IP"
    echo
    echo "VLESS_PORT=$VLESS_PORT"
    echo "VLESS_UUID=$VLESS_UUID"
    echo "VLESS_PUBKEY=$VLESS_PUBKEY"
    echo "VLESS_SHORTID=$VLESS_SHORTID"
    echo "VLESS_SNI=$VLESS_SNI"
    echo
    echo "HY2_PORT=$HY2_PORT"
    echo "HY2_PASSWORD=$HY2_PASSWORD"
    echo
    echo "API_SECRET=$API_SECRET"
    echo
    if [ -n "$TS_AUTHKEY" ]; then
        echo "TS_AUTHKEY=$TS_AUTHKEY"
        echo "TS_LOGIN_SERVER=$TS_LOGIN_SERVER"
    fi
} > "$TMP_FILE"
mv "$TMP_FILE" "$ENV_FILE"
chmod 600 "$ENV_FILE"
trap - EXIT

echo
echo "✓ Wrote $ENV_FILE (mode 600)"
echo
cat <<'NEXT'
Next steps:
  1. Push to Mudi (replace IP if your LAN is different):
       scp mudi.env provision-mudi.sh root@192.168.8.1:/tmp/

  2. Run on Mudi:
       ssh root@192.168.8.1
       cd /tmp
       set -a; . ./mudi.env; set +a
       ./provision-mudi.sh

  3. In GL Web UI, finish the WireGuard peer setup (endpoint shown at end
     of provision-mudi.sh output). Then toggle the screen VPN switch.
NEXT
